// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	// =============================================
	// EXAM PARTICIPANTS
	// =============================================
	AddParticipant(ctx context.Context, arg AddParticipantParams) (ExamParticipant, error)
	// =============================================
	// EXAM PROBLEMS
	// =============================================
	AddProblemToExam(ctx context.Context, arg AddProblemToExamParams) (ExamProblem, error)
	CountCorrectSubmissions(ctx context.Context, userID int64) (int64, error)
	CountProblems(ctx context.Context) (int64, error)
	CountProblemsByDifficulty(ctx context.Context) ([]CountProblemsByDifficultyRow, error)
	CountProblemsPerTopic(ctx context.Context) ([]CountProblemsPerTopicRow, error)
	CountUserExamSubmissions(ctx context.Context, arg CountUserExamSubmissionsParams) (int64, error)
	CountUserSubmissions(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	// =============================================
	// EXAMS
	// =============================================
	CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error)
	// =============================================
	// EXAM SUBMISSIONS
	// =============================================
	CreateExamSubmission(ctx context.Context, arg CreateExamSubmissionParams) (ExamSubmission, error)
	CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id int64) error
	DeleteExam(ctx context.Context, id int64) error
	DeleteProblem(ctx context.Context, id int64) error
	DeleteTopic(ctx context.Context, id int32) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetExamByID(ctx context.Context, id int64) (GetExamByIDRow, error)
	GetExamResults(ctx context.Context, examID int64) ([]GetExamResultsRow, error)
	GetExamSubmission(ctx context.Context, arg GetExamSubmissionParams) (ExamSubmission, error)
	GetLatestSubmission(ctx context.Context, arg GetLatestSubmissionParams) (Submission, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (GetParticipantRow, error)
	GetProblemByID(ctx context.Context, id int64) (Problem, error)
	GetProblemBySlug(ctx context.Context, slug string) (Problem, error)
	GetProblemWithUserProgress(ctx context.Context, arg GetProblemWithUserProgressParams) (GetProblemWithUserProgressRow, error)
	GetSubmissionByID(ctx context.Context, id int64) (GetSubmissionByIDRow, error)
	GetTopicByID(ctx context.Context, id int32) (Topic, error)
	GetTopicBySlug(ctx context.Context, slug string) (Topic, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByIdentifier(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserProgress(ctx context.Context, arg GetUserProgressParams) (UserProgress, error)
	GetUserStats(ctx context.Context, userID int64) (GetUserStatsRow, error)
	GetUserStatsByDifficulty(ctx context.Context, userID int64) ([]GetUserStatsByDifficultyRow, error)
	ListExamParticipants(ctx context.Context, examID int64) ([]ListExamParticipantsRow, error)
	ListExamProblems(ctx context.Context, examID int64) ([]ListExamProblemsRow, error)
	ListExams(ctx context.Context, arg ListExamsParams) ([]ListExamsRow, error)
	ListExamsByLecturer(ctx context.Context, arg ListExamsByLecturerParams) ([]ListExamsByLecturerRow, error)
	ListProblems(ctx context.Context, arg ListProblemsParams) ([]ListProblemsRow, error)
	ListProblemsByDifficulty(ctx context.Context, arg ListProblemsByDifficultyParams) ([]ListProblemsByDifficultyRow, error)
	ListProblemsByTopic(ctx context.Context, arg ListProblemsByTopicParams) ([]ListProblemsByTopicRow, error)
	ListPublicExams(ctx context.Context, arg ListPublicExamsParams) ([]ListPublicExamsRow, error)
	ListRecentAttempts(ctx context.Context, arg ListRecentAttemptsParams) ([]ListRecentAttemptsRow, error)
	ListSolvedProblems(ctx context.Context, arg ListSolvedProblemsParams) ([]ListSolvedProblemsRow, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListUserExamSubmissions(ctx context.Context, arg ListUserExamSubmissionsParams) ([]ListUserExamSubmissionsRow, error)
	ListUserExams(ctx context.Context, userID int64) ([]ListUserExamsRow, error)
	ListUserSubmissions(ctx context.Context, arg ListUserSubmissionsParams) ([]ListUserSubmissionsRow, error)
	ListUserSubmissionsForProblem(ctx context.Context, arg ListUserSubmissionsForProblemParams) ([]Submission, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	MarkProblemSolved(ctx context.Context, arg MarkProblemSolvedParams) (UserProgress, error)
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	RemoveProblemFromExam(ctx context.Context, arg RemoveProblemFromExamParams) error
	StartExam(ctx context.Context, arg StartExamParams) (ExamParticipant, error)
	SubmitExam(ctx context.Context, arg SubmitExamParams) (ExamParticipant, error)
	UpdateExam(ctx context.Context, arg UpdateExamParams) (Exam, error)
	UpdateExamProblemPoints(ctx context.Context, arg UpdateExamProblemPointsParams) (ExamProblem, error)
	UpdateExamStatus(ctx context.Context, arg UpdateExamStatusParams) (Exam, error)
	UpdateParticipantScore(ctx context.Context, arg UpdateParticipantScoreParams) (ExamParticipant, error)
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpsertProgress(ctx context.Context, arg UpsertProgressParams) (UserProgress, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
