// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: class.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClassMember = `-- name: AddClassMember :one

INSERT INTO class_members (class_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, class_id, user_id, role, joined_at
`

type AddClassMemberParams struct {
	ClassID int64   `json:"classId"`
	UserID  int64   `json:"userId"`
	Role    *string `json:"role"`
}

// =============================================
// CLASS_MEMBERS QUERIES
// =============================================
func (q *Queries) AddClassMember(ctx context.Context, arg AddClassMemberParams) (ClassMember, error) {
	row := q.db.QueryRow(ctx, addClassMember, arg.ClassID, arg.UserID, arg.Role)
	var i ClassMember
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const assignExamToClass = `-- name: AssignExamToClass :one

INSERT INTO class_exams (class_id, exam_id)
VALUES ($1, $2)
RETURNING id, class_id, exam_id, assigned_at
`

type AssignExamToClassParams struct {
	ClassID int64 `json:"classId"`
	ExamID  int64 `json:"examId"`
}

// =============================================
// CLASS_EXAMS QUERIES
// =============================================
func (q *Queries) AssignExamToClass(ctx context.Context, arg AssignExamToClassParams) (ClassExam, error) {
	row := q.db.QueryRow(ctx, assignExamToClass, arg.ClassID, arg.ExamID)
	var i ClassExam
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.ExamID,
		&i.AssignedAt,
	)
	return i, err
}

const countClassMembers = `-- name: CountClassMembers :one
SELECT COUNT(*) as count FROM class_members WHERE class_id = $1
`

func (q *Queries) CountClassMembers(ctx context.Context, classID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClassMembers, classID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClass = `-- name: CreateClass :one

INSERT INTO classes (name, description, code, created_by, semester, year)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, code, description, created_by, semester, year, is_active, created_at, updated_at
`

type CreateClassParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Code        string  `json:"code"`
	CreatedBy   int64   `json:"createdBy"`
	Semester    int32   `json:"semester"`
	Year        int32   `json:"year"`
}

// =============================================
// CLASSES QUERIES
// =============================================
func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.CreatedBy,
		arg.Semester,
		arg.Year,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedBy,
		&i.Semester,
		&i.Year,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateClass = `-- name: DeactivateClass :exec
UPDATE classes SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateClass(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateClass, id)
	return err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const getClassByCode = `-- name: GetClassByCode :one
SELECT id, name, code, description, created_by, semester, year, is_active, created_at, updated_at FROM classes WHERE code = $1
`

func (q *Queries) GetClassByCode(ctx context.Context, code string) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByCode, code)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedBy,
		&i.Semester,
		&i.Year,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, name, code, description, created_by, semester, year, is_active, created_at, updated_at FROM classes WHERE id = $1
`

func (q *Queries) GetClassByID(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedBy,
		&i.Semester,
		&i.Year,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassExamByID = `-- name: GetClassExamByID :one
SELECT ce.id, ce.class_id, e.id, e.title, e.description, e.created_by, e.start_time, e.end_time, e.duration_minutes, e.allowed_databases, e.allow_ai_assistance, e.shuffle_problems, e.show_result_immediately, e.max_attempts, e.is_public, e.status, e.created_at, e.updated_at FROM class_exams ce
JOIN exams e ON ce.exam_id = e.id
WHERE ce.id = $1
`

type GetClassExamByIDRow struct {
	ID                    int64              `json:"id"`
	ClassID               int64              `json:"classId"`
	ID_2                  int64              `json:"id2"`
	Title                 string             `json:"title"`
	Description           *string            `json:"description"`
	CreatedBy             int64              `json:"createdBy"`
	StartTime             pgtype.Timestamptz `json:"startTime"`
	EndTime               pgtype.Timestamptz `json:"endTime"`
	DurationMinutes       int32              `json:"durationMinutes"`
	AllowedDatabases      []string           `json:"allowedDatabases"`
	AllowAiAssistance     *bool              `json:"allowAiAssistance"`
	ShuffleProblems       *bool              `json:"shuffleProblems"`
	ShowResultImmediately *bool              `json:"showResultImmediately"`
	MaxAttempts           *int32             `json:"maxAttempts"`
	IsPublic              *bool              `json:"isPublic"`
	Status                *string            `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetClassExamByID(ctx context.Context, id int64) (GetClassExamByIDRow, error) {
	row := q.db.QueryRow(ctx, getClassExamByID, id)
	var i GetClassExamByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.ID_2,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.AllowedDatabases,
		&i.AllowAiAssistance,
		&i.ShuffleProblems,
		&i.ShowResultImmediately,
		&i.MaxAttempts,
		&i.IsPublic,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassMember = `-- name: GetClassMember :one
SELECT id, class_id, user_id, role, joined_at FROM class_members 
WHERE class_id = $1 AND user_id = $2
`

type GetClassMemberParams struct {
	ClassID int64 `json:"classId"`
	UserID  int64 `json:"userId"`
}

func (q *Queries) GetClassMember(ctx context.Context, arg GetClassMemberParams) (ClassMember, error) {
	row := q.db.QueryRow(ctx, getClassMember, arg.ClassID, arg.UserID)
	var i ClassMember
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getStudentClasses = `-- name: GetStudentClasses :many
SELECT c.id, c.name, c.code, c.description, c.created_by, c.semester, c.year, c.is_active, c.created_at, c.updated_at FROM classes c
JOIN class_members cm ON c.id = cm.class_id
WHERE cm.user_id = $1 AND c.is_active = TRUE
ORDER BY c.created_at DESC
`

func (q *Queries) GetStudentClasses(ctx context.Context, userID int64) ([]Class, error) {
	rows, err := q.db.Query(ctx, getStudentClasses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedBy,
			&i.Semester,
			&i.Year,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassExams = `-- name: ListClassExams :many
SELECT ce.id, e.id, e.title, e.description, e.created_by, e.start_time, e.end_time, e.duration_minutes, e.allowed_databases, e.allow_ai_assistance, e.shuffle_problems, e.show_result_immediately, e.max_attempts, e.is_public, e.status, e.created_at, e.updated_at FROM class_exams ce
JOIN exams e ON ce.exam_id = e.id
WHERE ce.class_id = $1
ORDER BY e.start_time DESC
`

type ListClassExamsRow struct {
	ID                    int64              `json:"id"`
	ID_2                  int64              `json:"id2"`
	Title                 string             `json:"title"`
	Description           *string            `json:"description"`
	CreatedBy             int64              `json:"createdBy"`
	StartTime             pgtype.Timestamptz `json:"startTime"`
	EndTime               pgtype.Timestamptz `json:"endTime"`
	DurationMinutes       int32              `json:"durationMinutes"`
	AllowedDatabases      []string           `json:"allowedDatabases"`
	AllowAiAssistance     *bool              `json:"allowAiAssistance"`
	ShuffleProblems       *bool              `json:"shuffleProblems"`
	ShowResultImmediately *bool              `json:"showResultImmediately"`
	MaxAttempts           *int32             `json:"maxAttempts"`
	IsPublic              *bool              `json:"isPublic"`
	Status                *string            `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListClassExams(ctx context.Context, classID int64) ([]ListClassExamsRow, error) {
	rows, err := q.db.Query(ctx, listClassExams, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassExamsRow{}
	for rows.Next() {
		var i ListClassExamsRow
		if err := rows.Scan(
			&i.ID,
			&i.ID_2,
			&i.Title,
			&i.Description,
			&i.CreatedBy,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.AllowedDatabases,
			&i.AllowAiAssistance,
			&i.ShuffleProblems,
			&i.ShowResultImmediately,
			&i.MaxAttempts,
			&i.IsPublic,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassMembers = `-- name: ListClassMembers :many
SELECT cm.id, cm.user_id, cm.role, cm.joined_at, u.email, u.full_name
FROM class_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.class_id = $1
ORDER BY cm.joined_at DESC
LIMIT $2 OFFSET $3
`

type ListClassMembersParams struct {
	ClassID int64 `json:"classId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListClassMembersRow struct {
	ID       int64              `json:"id"`
	UserID   int64              `json:"userId"`
	Role     *string            `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joinedAt"`
	Email    string             `json:"email"`
	FullName string             `json:"fullName"`
}

func (q *Queries) ListClassMembers(ctx context.Context, arg ListClassMembersParams) ([]ListClassMembersRow, error) {
	rows, err := q.db.Query(ctx, listClassMembers, arg.ClassID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassMembersRow{}
	for rows.Next() {
		var i ListClassMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByLecturer = `-- name: ListClassesByLecturer :many
SELECT id, name, code, description, created_by, semester, year, is_active, created_at, updated_at FROM classes 
WHERE created_by = $1 AND is_active = TRUE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListClassesByLecturerParams struct {
	CreatedBy int64 `json:"createdBy"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListClassesByLecturer(ctx context.Context, arg ListClassesByLecturerParams) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByLecturer, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedBy,
			&i.Semester,
			&i.Year,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClassMember = `-- name: RemoveClassMember :exec
DELETE FROM class_members 
WHERE class_id = $1 AND user_id = $2
`

type RemoveClassMemberParams struct {
	ClassID int64 `json:"classId"`
	UserID  int64 `json:"userId"`
}

func (q *Queries) RemoveClassMember(ctx context.Context, arg RemoveClassMemberParams) error {
	_, err := q.db.Exec(ctx, removeClassMember, arg.ClassID, arg.UserID)
	return err
}

const removeExamFromClass = `-- name: RemoveExamFromClass :exec
DELETE FROM class_exams 
WHERE class_id = $1 AND exam_id = $2
`

type RemoveExamFromClassParams struct {
	ClassID int64 `json:"classId"`
	ExamID  int64 `json:"examId"`
}

func (q *Queries) RemoveExamFromClass(ctx context.Context, arg RemoveExamFromClassParams) error {
	_, err := q.db.Exec(ctx, removeExamFromClass, arg.ClassID, arg.ExamID)
	return err
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes 
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    semester = COALESCE($4, semester),
    year = COALESCE($5, year),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, description, created_by, semester, year, is_active, created_at, updated_at
`

type UpdateClassParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Semester    int32   `json:"semester"`
	Year        int32   `json:"year"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Semester,
		arg.Year,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedBy,
		&i.Semester,
		&i.Year,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
