// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiGeneratedContent struct {
	ID                 int64              `json:"id"`
	PdfUploadID        *int64             `json:"pdfUploadId"`
	ProblemNumber      *int32             `json:"problemNumber"`
	ContentType        string             `json:"contentType"`
	OriginalContent    *string            `json:"originalContent"`
	AiGeneratedContent *string            `json:"aiGeneratedContent"`
	ConfidenceScore    pgtype.Numeric     `json:"confidenceScore"`
	AiProvider         *string            `json:"aiProvider"`
	IsApproved         *bool              `json:"isApproved"`
	LecturerNotes      *string            `json:"lecturerNotes"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type Class struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Code        string             `json:"code"`
	CreatedBy   int64              `json:"createdBy"`
	Semester    *string            `json:"semester"`
	Year        *int32             `json:"year"`
	IsActive    *bool              `json:"isActive"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type ClassExam struct {
	ID        int64              `json:"id"`
	ClassID   int64              `json:"classId"`
	ExamID    int64              `json:"examId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type ClassMember struct {
	ID       int64              `json:"id"`
	ClassID  int64              `json:"classId"`
	UserID   int64              `json:"userId"`
	Role     *string            `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joinedAt"`
}

type Exam struct {
	ID                    int64              `json:"id"`
	Title                 string             `json:"title"`
	Description           *string            `json:"description"`
	CreatedBy             int64              `json:"createdBy"`
	StartTime             pgtype.Timestamptz `json:"startTime"`
	EndTime               pgtype.Timestamptz `json:"endTime"`
	DurationMinutes       int32              `json:"durationMinutes"`
	AllowedDatabases      []string           `json:"allowedDatabases"`
	AllowAiAssistance     *bool              `json:"allowAiAssistance"`
	ShuffleProblems       *bool              `json:"shuffleProblems"`
	ShowResultImmediately *bool              `json:"showResultImmediately"`
	MaxAttempts           *int32             `json:"maxAttempts"`
	IsPublic              *bool              `json:"isPublic"`
	Status                *string            `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type ExamParticipant struct {
	ID          int64              `json:"id"`
	ExamID      int64              `json:"examId"`
	UserID      int64              `json:"userId"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	SubmittedAt pgtype.Timestamptz `json:"submittedAt"`
	TotalScore  pgtype.Numeric     `json:"totalScore"`
	Status      *string            `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type ExamProblem struct {
	ID              int64   `json:"id"`
	ExamID          int64   `json:"examId"`
	ProblemID       int64   `json:"problemId"`
	Points          *int32  `json:"points"`
	SortOrder       *int32  `json:"sortOrder"`
	ScoringMode     *string `json:"scoringMode"`
	ReferenceAnswer *string `json:"referenceAnswer"`
}

type ExamSubmission struct {
	ID              int64              `json:"id"`
	ExamID          int64              `json:"examId"`
	ExamProblemID   int64              `json:"examProblemId"`
	UserID          int64              `json:"userId"`
	Code            string             `json:"code"`
	DatabaseType    string             `json:"databaseType"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ExpectedOutput  []byte             `json:"expectedOutput"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	Score           pgtype.Numeric     `json:"score"`
	AttemptNumber   *int32             `json:"attemptNumber"`
	SubmittedAt     pgtype.Timestamptz `json:"submittedAt"`
	GradedBy        *int64             `json:"gradedBy"`
	GradedAt        pgtype.Timestamptz `json:"gradedAt"`
	TestCaseResults []byte             `json:"testCaseResults"`
}

type ExcelExport struct {
	ID         int64              `json:"id"`
	ExamID     *int64             `json:"examId"`
	ExportType string             `json:"exportType"`
	FilePath   *string            `json:"filePath"`
	FileName   *string            `json:"fileName"`
	CreatedBy  *int64             `json:"createdBy"`
	RowCount   *int32             `json:"rowCount"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type OutboxEvent struct {
	ID          uuid.UUID        `json:"id"`
	Topic       string           `json:"topic"`
	Payload     json.RawMessage  `json:"payload"`
	Status      string           `json:"status"`
	RetryCount  int32            `json:"retryCount"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	PublishedAt pgtype.Timestamp `json:"publishedAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type PdfUpload struct {
	ID               int64              `json:"id"`
	LecturerID       int64              `json:"lecturerId"`
	FilePath         string             `json:"filePath"`
	FileName         string             `json:"fileName"`
	OriginalFilename *string            `json:"originalFilename"`
	Status           string             `json:"status"`
	ExtractionResult []byte             `json:"extractionResult"`
	ErrorMessage     *string            `json:"errorMessage"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
}

type Permission struct {
	ID           int32            `json:"id"`
	ResourceType string           `json:"resourceType"`
	Action       string           `json:"action"`
	Description  *string          `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type PermissionAuditLog struct {
	ID                 int32            `json:"id"`
	Action             string           `json:"action"`
	TargetUserID       *int32           `json:"targetUserId"`
	TargetRoleID       *int32           `json:"targetRoleId"`
	TargetResourceType *string          `json:"targetResourceType"`
	TargetResourceID   *int64           `json:"targetResourceId"`
	PerformedBy        int32            `json:"performedBy"`
	Details            []byte           `json:"details"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

type Problem struct {
	ID                 int64              `json:"id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	Difficulty         string             `json:"difficulty"`
	TopicID            *int32             `json:"topicId"`
	CreatedBy          *int64             `json:"createdBy"`
	InitScript         string             `json:"initScript"`
	SolutionQuery      string             `json:"solutionQuery"`
	SupportedDatabases []string           `json:"supportedDatabases"`
	OrderMatters       *bool              `json:"orderMatters"`
	Hints              []byte             `json:"hints"`
	SampleOutput       []byte             `json:"sampleOutput"`
	IsPublic           *bool              `json:"isPublic"`
	IsActive           *bool              `json:"isActive"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	AiGenerated        *bool              `json:"aiGenerated"`
	AiProvider         *string            `json:"aiProvider"`
	AiConfidenceScore  pgtype.Numeric     `json:"aiConfidenceScore"`
}

type ProblemReviewQueue struct {
	ID            int64              `json:"id"`
	PdfUploadID   *int64             `json:"pdfUploadId"`
	ProblemNumber *int32             `json:"problemNumber"`
	ProblemDraft  json.RawMessage    `json:"problemDraft"`
	Status        string             `json:"status"`
	ReviewerID    *int64             `json:"reviewerId"`
	ReviewNotes   *string            `json:"reviewNotes"`
	EditsMade     []byte             `json:"editsMade"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewedAt"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type ProblemTestCase struct {
	ID            int64              `json:"id"`
	ProblemID     int64              `json:"problemId"`
	Name          *string            `json:"name"`
	Description   *string            `json:"description"`
	InitScript    string             `json:"initScript"`
	SolutionQuery string             `json:"solutionQuery"`
	Weight        *int32             `json:"weight"`
	IsHidden      *bool              `json:"isHidden"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type ProcessedEvent struct {
	EventID       string           `json:"eventId"`
	ConsumerGroup string           `json:"consumerGroup"`
	ProcessedAt   pgtype.Timestamp `json:"processedAt"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Revoked   *bool              `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ResourceAccessControl struct {
	ID             int32            `json:"id"`
	ResourceType   string           `json:"resourceType"`
	ResourceID     int64            `json:"resourceId"`
	UserID         int32            `json:"userId"`
	PermissionType string           `json:"permissionType"`
	GrantedAt      pgtype.Timestamp `json:"grantedAt"`
	GrantedBy      *int32           `json:"grantedBy"`
}

type Role struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	IsExtensible *bool            `json:"isExtensible"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type RolePermission struct {
	ID           int32            `json:"id"`
	RoleID       int32            `json:"roleId"`
	PermissionID int32            `json:"permissionId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type Submission struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"userId"`
	ProblemID       int64              `json:"problemId"`
	Code            string             `json:"code"`
	DatabaseType    string             `json:"databaseType"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ExpectedOutput  []byte             `json:"expectedOutput"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	SubmittedAt     pgtype.Timestamptz `json:"submittedAt"`
	Score           pgtype.Numeric     `json:"score"`
	TotalTestCases  *int32             `json:"totalTestCases"`
	PassedTestCases *int32             `json:"passedTestCases"`
}

type SubmissionTestResult struct {
	ID              int64              `json:"id"`
	SubmissionID    int64              `json:"submissionId"`
	TestCaseID      int64              `json:"testCaseId"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type TestCaseTemplate struct {
	ID               int64              `json:"id"`
	ProblemID        *int64             `json:"problemId"`
	TestCaseNumber   *int32             `json:"testCaseNumber"`
	Description      *string            `json:"description"`
	SchemaSql        string             `json:"schemaSql"`
	TestDataSql      string             `json:"testDataSql"`
	ExpectedOutput   json.RawMessage    `json:"expectedOutput"`
	IsPublic         *bool              `json:"isPublic"`
	Difficulty       *string            `json:"difficulty"`
	CreatedBy        *int64             `json:"createdBy"`
	IsValidated      *bool              `json:"isValidated"`
	ValidationStatus *string            `json:"validationStatus"`
	ValidationError  *string            `json:"validationError"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Topic struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Icon        *string            `json:"icon"`
	SortOrder   *int32             `json:"sortOrder"`
	IsActive    *bool              `json:"isActive"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"passwordHash"`
	FullName     string             `json:"fullName"`
	Role         string             `json:"role"`
	StudentID    *string            `json:"studentId"`
	AvatarUrl    *string            `json:"avatarUrl"`
	IsActive     *bool              `json:"isActive"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type UserProgress struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"userId"`
	ProblemID        int64              `json:"problemId"`
	IsSolved         *bool              `json:"isSolved"`
	Attempts         *int32             `json:"attempts"`
	BestTimeMs       *int32             `json:"bestTimeMs"`
	FirstAttemptedAt pgtype.Timestamptz `json:"firstAttemptedAt"`
	LastAttemptedAt  pgtype.Timestamptz `json:"lastAttemptedAt"`
	SolvedAt         pgtype.Timestamptz `json:"solvedAt"`
}

type UserRole struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"userId"`
	RoleID     int32            `json:"roleId"`
	AssignedAt pgtype.Timestamp `json:"assignedAt"`
	AssignedBy *int32           `json:"assignedBy"`
}
