// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Exam struct {
	ID                    int64              `json:"id"`
	Title                 string             `json:"title"`
	Description           *string            `json:"description"`
	CreatedBy             int64              `json:"createdBy"`
	StartTime             pgtype.Timestamptz `json:"startTime"`
	EndTime               pgtype.Timestamptz `json:"endTime"`
	DurationMinutes       int32              `json:"durationMinutes"`
	AllowedDatabases      []string           `json:"allowedDatabases"`
	AllowAiAssistance     *bool              `json:"allowAiAssistance"`
	ShuffleProblems       *bool              `json:"shuffleProblems"`
	ShowResultImmediately *bool              `json:"showResultImmediately"`
	MaxAttempts           *int32             `json:"maxAttempts"`
	IsPublic              *bool              `json:"isPublic"`
	Status                *string            `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type ExamParticipant struct {
	ID          int64              `json:"id"`
	ExamID      int64              `json:"examId"`
	UserID      int64              `json:"userId"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	SubmittedAt pgtype.Timestamptz `json:"submittedAt"`
	TotalScore  pgtype.Numeric     `json:"totalScore"`
	Status      *string            `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type ExamProblem struct {
	ID        int64  `json:"id"`
	ExamID    int64  `json:"examId"`
	ProblemID int64  `json:"problemId"`
	Points    *int32 `json:"points"`
	SortOrder *int32 `json:"sortOrder"`
}

type ExamSubmission struct {
	ID              int64              `json:"id"`
	ExamID          int64              `json:"examId"`
	ExamProblemID   int64              `json:"examProblemId"`
	UserID          int64              `json:"userId"`
	Code            string             `json:"code"`
	DatabaseType    string             `json:"databaseType"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ExpectedOutput  []byte             `json:"expectedOutput"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	Score           pgtype.Numeric     `json:"score"`
	AttemptNumber   *int32             `json:"attemptNumber"`
	SubmittedAt     pgtype.Timestamptz `json:"submittedAt"`
}

type OutboxEvent struct {
	ID          uuid.UUID        `json:"id"`
	Topic       string           `json:"topic"`
	Payload     json.RawMessage  `json:"payload"`
	Status      string           `json:"status"`
	RetryCount  int32            `json:"retryCount"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	PublishedAt pgtype.Timestamp `json:"publishedAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Permission struct {
	ID           int32            `json:"id"`
	ResourceType string           `json:"resourceType"`
	Action       string           `json:"action"`
	Description  *string          `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type PermissionAuditLog struct {
	ID                 int32            `json:"id"`
	Action             string           `json:"action"`
	TargetUserID       *int32           `json:"targetUserId"`
	TargetRoleID       *int32           `json:"targetRoleId"`
	TargetResourceType *string          `json:"targetResourceType"`
	TargetResourceID   *int64           `json:"targetResourceId"`
	PerformedBy        int32            `json:"performedBy"`
	Details            []byte           `json:"details"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

type Problem struct {
	ID                 int64              `json:"id"`
	Title              string             `json:"title"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	Difficulty         string             `json:"difficulty"`
	TopicID            *int32             `json:"topicId"`
	CreatedBy          *int64             `json:"createdBy"`
	InitScript         string             `json:"initScript"`
	SolutionQuery      string             `json:"solutionQuery"`
	SupportedDatabases []string           `json:"supportedDatabases"`
	OrderMatters       *bool              `json:"orderMatters"`
	Hints              []byte             `json:"hints"`
	SampleOutput       []byte             `json:"sampleOutput"`
	IsPublic           *bool              `json:"isPublic"`
	IsActive           *bool              `json:"isActive"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type ProblemTestCase struct {
	ID            int64              `json:"id"`
	ProblemID     int64              `json:"problemId"`
	Name          *string            `json:"name"`
	Description   *string            `json:"description"`
	InitScript    string             `json:"initScript"`
	SolutionQuery string             `json:"solutionQuery"`
	Weight        *int32             `json:"weight"`
	IsHidden      *bool              `json:"isHidden"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type ProcessedEvent struct {
	EventID       string           `json:"eventId"`
	ConsumerGroup string           `json:"consumerGroup"`
	ProcessedAt   pgtype.Timestamp `json:"processedAt"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Revoked   *bool              `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ResourceAccessControl struct {
	ID             int32            `json:"id"`
	ResourceType   string           `json:"resourceType"`
	ResourceID     int64            `json:"resourceId"`
	UserID         int32            `json:"userId"`
	PermissionType string           `json:"permissionType"`
	GrantedAt      pgtype.Timestamp `json:"grantedAt"`
	GrantedBy      *int32           `json:"grantedBy"`
}

type Role struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	IsExtensible *bool            `json:"isExtensible"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type RolePermission struct {
	ID           int32            `json:"id"`
	RoleID       int32            `json:"roleId"`
	PermissionID int32            `json:"permissionId"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}

type Submission struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"userId"`
	ProblemID       int64              `json:"problemId"`
	Code            string             `json:"code"`
	DatabaseType    string             `json:"databaseType"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ExpectedOutput  []byte             `json:"expectedOutput"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	SubmittedAt     pgtype.Timestamptz `json:"submittedAt"`
	Score           pgtype.Numeric     `json:"score"`
	TotalTestCases  *int32             `json:"totalTestCases"`
	PassedTestCases *int32             `json:"passedTestCases"`
}

type SubmissionTestResult struct {
	ID              int64              `json:"id"`
	SubmissionID    int64              `json:"submissionId"`
	TestCaseID      int64              `json:"testCaseId"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type Topic struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Icon        *string            `json:"icon"`
	SortOrder   *int32             `json:"sortOrder"`
	IsActive    *bool              `json:"isActive"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"passwordHash"`
	FullName     string             `json:"fullName"`
	Role         string             `json:"role"`
	StudentID    *string            `json:"studentId"`
	AvatarUrl    *string            `json:"avatarUrl"`
	IsActive     *bool              `json:"isActive"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type UserProgress struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"userId"`
	ProblemID        int64              `json:"problemId"`
	IsSolved         *bool              `json:"isSolved"`
	Attempts         *int32             `json:"attempts"`
	BestTimeMs       *int32             `json:"bestTimeMs"`
	FirstAttemptedAt pgtype.Timestamptz `json:"firstAttemptedAt"`
	LastAttemptedAt  pgtype.Timestamptz `json:"lastAttemptedAt"`
	SolvedAt         pgtype.Timestamptz `json:"solvedAt"`
}

type UserRole struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"userId"`
	RoleID     int32            `json:"roleId"`
	AssignedAt pgtype.Timestamp `json:"assignedAt"`
	AssignedBy *int32           `json:"assignedBy"`
}
