// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const fetchPendingEvents = `-- name: FetchPendingEvents :many
SELECT id, topic, payload
FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type FetchPendingEventsRow struct {
	ID      uuid.UUID       `json:"id"`
	Topic   string          `json:"topic"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) FetchPendingEvents(ctx context.Context, limit int32) ([]FetchPendingEventsRow, error) {
	rows, err := q.db.Query(ctx, fetchPendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchPendingEventsRow{}
	for rows.Next() {
		var i FetchPendingEventsRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(
    SELECT 1 FROM processed_events
    WHERE event_id = $1 AND consumer_group = $2
) as processed
`

type IsEventProcessedParams struct {
	EventID       string `json:"eventId"`
	ConsumerGroup string `json:"consumerGroup"`
}

func (q *Queries) IsEventProcessed(ctx context.Context, arg IsEventProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, arg.EventID, arg.ConsumerGroup)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE outbox_events
SET status = 'failed', retry_count = retry_count + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEventFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventFailed, id)
	return err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec

INSERT INTO processed_events (event_id, consumer_group, processed_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID       string `json:"eventId"`
	ConsumerGroup string `json:"consumerGroup"`
}

// =============================================
// PROCESSED EVENTS (for idempotent consumers)
// =============================================
func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.ConsumerGroup)
	return err
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE outbox_events
SET status = 'published', published_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventPublished, id)
	return err
}

const saveOutboxEvent = `-- name: SaveOutboxEvent :one

INSERT INTO outbox_events (id, topic, payload, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'pending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, topic, payload, status
`

type SaveOutboxEventParams struct {
	Topic   string          `json:"topic"`
	Payload json.RawMessage `json:"payload"`
}

type SaveOutboxEventRow struct {
	ID      uuid.UUID       `json:"id"`
	Topic   string          `json:"topic"`
	Payload json.RawMessage `json:"payload"`
	Status  string          `json:"status"`
}

// =============================================
// OUTBOX EVENTS
// =============================================
func (q *Queries) SaveOutboxEvent(ctx context.Context, arg SaveOutboxEventParams) (SaveOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, saveOutboxEvent, arg.Topic, arg.Payload)
	var i SaveOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.Status,
	)
	return i, err
}
