// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pdf.sql

package models

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIGeneratedContent = `-- name: CreateAIGeneratedContent :one

INSERT INTO ai_generated_content (
    pdf_upload_id, problem_number, content_type, original_content,
    ai_generated_content, confidence_score, ai_provider
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, pdf_upload_id, problem_number, content_type, original_content, ai_generated_content, confidence_score, ai_provider, is_approved, lecturer_notes, created_at, updated_at
`

type CreateAIGeneratedContentParams struct {
	PdfUploadID        int64          `json:"pdfUploadId"`
	ProblemNumber      int32          `json:"problemNumber"`
	ContentType        string         `json:"contentType"`
	OriginalContent    *string        `json:"originalContent"`
	AiGeneratedContent *string        `json:"aiGeneratedContent"`
	ConfidenceScore    pgtype.Numeric `json:"confidenceScore"`
	AiProvider         *string        `json:"aiProvider"`
}

// AI Generated Content Queries
func (q *Queries) CreateAIGeneratedContent(ctx context.Context, arg CreateAIGeneratedContentParams) (AiGeneratedContent, error) {
	row := q.db.QueryRow(ctx, createAIGeneratedContent,
		arg.PdfUploadID,
		arg.ProblemNumber,
		arg.ContentType,
		arg.OriginalContent,
		arg.AiGeneratedContent,
		arg.ConfidenceScore,
		arg.AiProvider,
	)
	var i AiGeneratedContent
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ContentType,
		&i.OriginalContent,
		&i.AiGeneratedContent,
		&i.ConfidenceScore,
		&i.AiProvider,
		&i.IsApproved,
		&i.LecturerNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExcelExport = `-- name: CreateExcelExport :one

INSERT INTO excel_exports (
    exam_id, export_type, file_path, file_name, created_by, row_count
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, exam_id, export_type, file_path, file_name, created_by, row_count, created_at
`

type CreateExcelExportParams struct {
	ExamID     int64  `json:"examId"`
	ExportType string `json:"exportType"`
	FilePath   string `json:"filePath"`
	FileName   string `json:"fileName"`
	CreatedBy  int64  `json:"createdBy"`
	RowCount   *int32 `json:"rowCount"`
}

// Excel Export Queries
func (q *Queries) CreateExcelExport(ctx context.Context, arg CreateExcelExportParams) (ExcelExport, error) {
	row := q.db.QueryRow(ctx, createExcelExport,
		arg.ExamID,
		arg.ExportType,
		arg.FilePath,
		arg.FileName,
		arg.CreatedBy,
		arg.RowCount,
	)
	var i ExcelExport
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.ExportType,
		&i.FilePath,
		&i.FileName,
		&i.CreatedBy,
		&i.RowCount,
		&i.CreatedAt,
	)
	return i, err
}

const createPDFUpload = `-- name: CreatePDFUpload :one

INSERT INTO pdf_uploads (
    lecturer_id, file_path, file_name, original_filename, status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at
`

type CreatePDFUploadParams struct {
	LecturerID       int64  `json:"lecturerId"`
	FilePath         string `json:"filePath"`
	FileName         string `json:"fileName"`
	OriginalFilename string `json:"originalFilename"`
	Status           string `json:"status"`
}

// PDF Upload Queries
func (q *Queries) CreatePDFUpload(ctx context.Context, arg CreatePDFUploadParams) (PdfUpload, error) {
	row := q.db.QueryRow(ctx, createPDFUpload,
		arg.LecturerID,
		arg.FilePath,
		arg.FileName,
		arg.OriginalFilename,
		arg.Status,
	)
	var i PdfUpload
	err := row.Scan(
		&i.ID,
		&i.LecturerID,
		&i.FilePath,
		&i.FileName,
		&i.OriginalFilename,
		&i.Status,
		&i.ExtractionResult,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProblemReviewQueue = `-- name: CreateProblemReviewQueue :one

INSERT INTO problem_review_queue (
    pdf_upload_id, problem_number, problem_draft, status
)
VALUES ($1, $2, $3, $4)
RETURNING id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at
`

type CreateProblemReviewQueueParams struct {
	PdfUploadID   int64           `json:"pdfUploadId"`
	ProblemNumber int32           `json:"problemNumber"`
	ProblemDraft  json.RawMessage `json:"problemDraft"`
	Status        string          `json:"status"`
}

// Problem Review Queue Queries
func (q *Queries) CreateProblemReviewQueue(ctx context.Context, arg CreateProblemReviewQueueParams) (ProblemReviewQueue, error) {
	row := q.db.QueryRow(ctx, createProblemReviewQueue,
		arg.PdfUploadID,
		arg.ProblemNumber,
		arg.ProblemDraft,
		arg.Status,
	)
	var i ProblemReviewQueue
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ProblemDraft,
		&i.EditsMade,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNotes,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTestCaseTemplate = `-- name: CreateTestCaseTemplate :one

INSERT INTO test_case_templates (
    problem_id, test_case_number, description, schema_sql,
    test_data_sql, expected_output, is_public, difficulty, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, problem_id, test_case_number, description, schema_sql, test_data_sql, expected_output, is_public, difficulty, is_validated, validation_status, validation_error, created_by, created_at
`

type CreateTestCaseTemplateParams struct {
	ProblemID      *int64  `json:"problemId"`
	TestCaseNumber int32   `json:"testCaseNumber"`
	Description    *string `json:"description"`
	SchemaSql      *string `json:"schemaSql"`
	TestDataSql    string  `json:"testDataSql"`
	ExpectedOutput []byte  `json:"expectedOutput"`
	IsPublic       *bool   `json:"isPublic"`
	Difficulty     *string `json:"difficulty"`
	CreatedBy      *int64  `json:"createdBy"`
}

// Test Case Templates Queries
func (q *Queries) CreateTestCaseTemplate(ctx context.Context, arg CreateTestCaseTemplateParams) (TestCaseTemplate, error) {
	row := q.db.QueryRow(ctx, createTestCaseTemplate,
		arg.ProblemID,
		arg.TestCaseNumber,
		arg.Description,
		arg.SchemaSql,
		arg.TestDataSql,
		arg.ExpectedOutput,
		arg.IsPublic,
		arg.Difficulty,
		arg.CreatedBy,
	)
	var i TestCaseTemplate
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.TestCaseNumber,
		&i.Description,
		&i.SchemaSql,
		&i.TestDataSql,
		&i.ExpectedOutput,
		&i.IsPublic,
		&i.Difficulty,
		&i.IsValidated,
		&i.ValidationStatus,
		&i.ValidationError,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAIGeneratedContentByProblem = `-- name: GetAIGeneratedContentByProblem :many
SELECT id, pdf_upload_id, problem_number, content_type, original_content, ai_generated_content, confidence_score, ai_provider, is_approved, lecturer_notes, created_at, updated_at FROM ai_generated_content
WHERE pdf_upload_id = $1 AND problem_number = $2
ORDER BY created_at DESC
`

type GetAIGeneratedContentByProblemParams struct {
	PdfUploadID   int64 `json:"pdfUploadId"`
	ProblemNumber int32 `json:"problemNumber"`
}

func (q *Queries) GetAIGeneratedContentByProblem(ctx context.Context, arg GetAIGeneratedContentByProblemParams) ([]AiGeneratedContent, error) {
	rows, err := q.db.Query(ctx, getAIGeneratedContentByProblem, arg.PdfUploadID, arg.ProblemNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiGeneratedContent{}
	for rows.Next() {
		var i AiGeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.PdfUploadID,
			&i.ProblemNumber,
			&i.ContentType,
			&i.OriginalContent,
			&i.AiGeneratedContent,
			&i.ConfidenceScore,
			&i.AiProvider,
			&i.IsApproved,
			&i.LecturerNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIGeneratedContentByType = `-- name: GetAIGeneratedContentByType :many
SELECT id, pdf_upload_id, problem_number, content_type, original_content, ai_generated_content, confidence_score, ai_provider, is_approved, lecturer_notes, created_at, updated_at FROM ai_generated_content
WHERE pdf_upload_id = $1 AND content_type = $2
ORDER BY problem_number
`

type GetAIGeneratedContentByTypeParams struct {
	PdfUploadID int64  `json:"pdfUploadId"`
	ContentType string `json:"contentType"`
}

func (q *Queries) GetAIGeneratedContentByType(ctx context.Context, arg GetAIGeneratedContentByTypeParams) ([]AiGeneratedContent, error) {
	rows, err := q.db.Query(ctx, getAIGeneratedContentByType, arg.PdfUploadID, arg.ContentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiGeneratedContent{}
	for rows.Next() {
		var i AiGeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.PdfUploadID,
			&i.ProblemNumber,
			&i.ContentType,
			&i.OriginalContent,
			&i.AiGeneratedContent,
			&i.ConfidenceScore,
			&i.AiProvider,
			&i.IsApproved,
			&i.LecturerNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExcelExportsByExam = `-- name: GetExcelExportsByExam :many
SELECT id, exam_id, export_type, file_path, file_name, created_by, row_count, created_at FROM excel_exports
WHERE exam_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetExcelExportsByExam(ctx context.Context, examID int64) ([]ExcelExport, error) {
	rows, err := q.db.Query(ctx, getExcelExportsByExam, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExcelExport{}
	for rows.Next() {
		var i ExcelExport
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.ExportType,
			&i.FilePath,
			&i.FileName,
			&i.CreatedBy,
			&i.RowCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestExcelExport = `-- name: GetLatestExcelExport :one
SELECT id, exam_id, export_type, file_path, file_name, created_by, row_count, created_at FROM excel_exports
WHERE exam_id = $1 AND export_type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestExcelExportParams struct {
	ExamID     int64  `json:"examId"`
	ExportType string `json:"exportType"`
}

func (q *Queries) GetLatestExcelExport(ctx context.Context, arg GetLatestExcelExportParams) (ExcelExport, error) {
	row := q.db.QueryRow(ctx, getLatestExcelExport, arg.ExamID, arg.ExportType)
	var i ExcelExport
	err := row.Scan(
		&i.ID,
		&i.ExamID,
		&i.ExportType,
		&i.FilePath,
		&i.FileName,
		&i.CreatedBy,
		&i.RowCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPDFUploadByID = `-- name: GetPDFUploadByID :one
SELECT id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at FROM pdf_uploads WHERE id = $1
`

func (q *Queries) GetPDFUploadByID(ctx context.Context, id int64) (PdfUpload, error) {
	row := q.db.QueryRow(ctx, getPDFUploadByID, id)
	var i PdfUpload
	err := row.Scan(
		&i.ID,
		&i.LecturerID,
		&i.FilePath,
		&i.FileName,
		&i.OriginalFilename,
		&i.Status,
		&i.ExtractionResult,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPDFUploadsByLecturer = `-- name: GetPDFUploadsByLecturer :many
SELECT id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at FROM pdf_uploads 
WHERE lecturer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPDFUploadsByLecturerParams struct {
	LecturerID int64 `json:"lecturerId"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) GetPDFUploadsByLecturer(ctx context.Context, arg GetPDFUploadsByLecturerParams) ([]PdfUpload, error) {
	rows, err := q.db.Query(ctx, getPDFUploadsByLecturer, arg.LecturerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PdfUpload{}
	for rows.Next() {
		var i PdfUpload
		if err := rows.Scan(
			&i.ID,
			&i.LecturerID,
			&i.FilePath,
			&i.FileName,
			&i.OriginalFilename,
			&i.Status,
			&i.ExtractionResult,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemReviewQueueByID = `-- name: GetProblemReviewQueueByID :one
SELECT id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at FROM problem_review_queue WHERE id = $1
`

func (q *Queries) GetProblemReviewQueueByID(ctx context.Context, id int64) (ProblemReviewQueue, error) {
	row := q.db.QueryRow(ctx, getProblemReviewQueueByID, id)
	var i ProblemReviewQueue
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ProblemDraft,
		&i.EditsMade,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNotes,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemReviewQueueByPDF = `-- name: GetProblemReviewQueueByPDF :many
SELECT id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at FROM problem_review_queue
WHERE pdf_upload_id = $1
ORDER BY problem_number
`

func (q *Queries) GetProblemReviewQueueByPDF(ctx context.Context, pdfUploadID int64) ([]ProblemReviewQueue, error) {
	rows, err := q.db.Query(ctx, getProblemReviewQueueByPDF, pdfUploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemReviewQueue{}
	for rows.Next() {
		var i ProblemReviewQueue
		if err := rows.Scan(
			&i.ID,
			&i.PdfUploadID,
			&i.ProblemNumber,
			&i.ProblemDraft,
			&i.EditsMade,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNotes,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblemReviewQueueByStatus = `-- name: GetProblemReviewQueueByStatus :many
SELECT id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at FROM problem_review_queue
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetProblemReviewQueueByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetProblemReviewQueueByStatus(ctx context.Context, arg GetProblemReviewQueueByStatusParams) ([]ProblemReviewQueue, error) {
	rows, err := q.db.Query(ctx, getProblemReviewQueueByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemReviewQueue{}
	for rows.Next() {
		var i ProblemReviewQueue
		if err := rows.Scan(
			&i.ID,
			&i.PdfUploadID,
			&i.ProblemNumber,
			&i.ProblemDraft,
			&i.EditsMade,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNotes,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTestCaseTemplates = `-- name: GetPublicTestCaseTemplates :many
SELECT id, problem_id, test_case_number, description, schema_sql, test_data_sql, expected_output, is_public, difficulty, is_validated, validation_status, validation_error, created_by, created_at FROM test_case_templates
WHERE problem_id = $1 AND is_public = TRUE
ORDER BY test_case_number
`

func (q *Queries) GetPublicTestCaseTemplates(ctx context.Context, problemID *int64) ([]TestCaseTemplate, error) {
	rows, err := q.db.Query(ctx, getPublicTestCaseTemplates, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCaseTemplate{}
	for rows.Next() {
		var i TestCaseTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.TestCaseNumber,
			&i.Description,
			&i.SchemaSql,
			&i.TestDataSql,
			&i.ExpectedOutput,
			&i.IsPublic,
			&i.Difficulty,
			&i.IsValidated,
			&i.ValidationStatus,
			&i.ValidationError,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestCaseTemplatesByProblem = `-- name: GetTestCaseTemplatesByProblem :many
SELECT id, problem_id, test_case_number, description, schema_sql, test_data_sql, expected_output, is_public, difficulty, is_validated, validation_status, validation_error, created_by, created_at FROM test_case_templates
WHERE problem_id = $1
ORDER BY test_case_number
`

func (q *Queries) GetTestCaseTemplatesByProblem(ctx context.Context, problemID *int64) ([]TestCaseTemplate, error) {
	rows, err := q.db.Query(ctx, getTestCaseTemplatesByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCaseTemplate{}
	for rows.Next() {
		var i TestCaseTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.TestCaseNumber,
			&i.Description,
			&i.SchemaSql,
			&i.TestDataSql,
			&i.ExpectedOutput,
			&i.IsPublic,
			&i.Difficulty,
			&i.IsValidated,
			&i.ValidationStatus,
			&i.ValidationError,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIGeneratedContentApproval = `-- name: UpdateAIGeneratedContentApproval :one
UPDATE ai_generated_content
SET 
    is_approved = $2,
    lecturer_notes = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, pdf_upload_id, problem_number, content_type, original_content, ai_generated_content, confidence_score, ai_provider, is_approved, lecturer_notes, created_at, updated_at
`

type UpdateAIGeneratedContentApprovalParams struct {
	ID            int64   `json:"id"`
	IsApproved    *bool   `json:"isApproved"`
	LecturerNotes *string `json:"lecturerNotes"`
}

func (q *Queries) UpdateAIGeneratedContentApproval(ctx context.Context, arg UpdateAIGeneratedContentApprovalParams) (AiGeneratedContent, error) {
	row := q.db.QueryRow(ctx, updateAIGeneratedContentApproval, arg.ID, arg.IsApproved, arg.LecturerNotes)
	var i AiGeneratedContent
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ContentType,
		&i.OriginalContent,
		&i.AiGeneratedContent,
		&i.ConfidenceScore,
		&i.AiProvider,
		&i.IsApproved,
		&i.LecturerNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePDFUploadError = `-- name: UpdatePDFUploadError :one
UPDATE pdf_uploads 
SET 
    status = 'failed',
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at
`

type UpdatePDFUploadErrorParams struct {
	ID           int64   `json:"id"`
	ErrorMessage *string `json:"errorMessage"`
}

func (q *Queries) UpdatePDFUploadError(ctx context.Context, arg UpdatePDFUploadErrorParams) (PdfUpload, error) {
	row := q.db.QueryRow(ctx, updatePDFUploadError, arg.ID, arg.ErrorMessage)
	var i PdfUpload
	err := row.Scan(
		&i.ID,
		&i.LecturerID,
		&i.FilePath,
		&i.FileName,
		&i.OriginalFilename,
		&i.Status,
		&i.ExtractionResult,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePDFUploadStatus = `-- name: UpdatePDFUploadStatus :one
UPDATE pdf_uploads 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at
`

type UpdatePDFUploadStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePDFUploadStatus(ctx context.Context, arg UpdatePDFUploadStatusParams) (PdfUpload, error) {
	row := q.db.QueryRow(ctx, updatePDFUploadStatus, arg.ID, arg.Status)
	var i PdfUpload
	err := row.Scan(
		&i.ID,
		&i.LecturerID,
		&i.FilePath,
		&i.FileName,
		&i.OriginalFilename,
		&i.Status,
		&i.ExtractionResult,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePDFUploadWithExtraction = `-- name: UpdatePDFUploadWithExtraction :one
UPDATE pdf_uploads 
SET 
    status = $2,
    extraction_result = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, lecturer_id, file_path, file_name, original_filename, status, extraction_result, error_message, created_at, updated_at
`

type UpdatePDFUploadWithExtractionParams struct {
	ID               int64  `json:"id"`
	Status           string `json:"status"`
	ExtractionResult []byte `json:"extractionResult"`
}

func (q *Queries) UpdatePDFUploadWithExtraction(ctx context.Context, arg UpdatePDFUploadWithExtractionParams) (PdfUpload, error) {
	row := q.db.QueryRow(ctx, updatePDFUploadWithExtraction, arg.ID, arg.Status, arg.ExtractionResult)
	var i PdfUpload
	err := row.Scan(
		&i.ID,
		&i.LecturerID,
		&i.FilePath,
		&i.FileName,
		&i.OriginalFilename,
		&i.Status,
		&i.ExtractionResult,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblemReviewDraft = `-- name: UpdateProblemReviewDraft :one
UPDATE problem_review_queue
SET 
    problem_draft = $2,
    edits_made = $3,
    status = 'editing',
    updated_at = NOW()
WHERE id = $1
RETURNING id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at
`

type UpdateProblemReviewDraftParams struct {
	ID           int64           `json:"id"`
	ProblemDraft json.RawMessage `json:"problemDraft"`
	EditsMade    []byte          `json:"editsMade"`
}

func (q *Queries) UpdateProblemReviewDraft(ctx context.Context, arg UpdateProblemReviewDraftParams) (ProblemReviewQueue, error) {
	row := q.db.QueryRow(ctx, updateProblemReviewDraft, arg.ID, arg.ProblemDraft, arg.EditsMade)
	var i ProblemReviewQueue
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ProblemDraft,
		&i.EditsMade,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNotes,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblemReviewStatus = `-- name: UpdateProblemReviewStatus :one
UPDATE problem_review_queue
SET 
    status = $2,
    reviewer_id = $3,
    review_notes = $4,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, pdf_upload_id, problem_number, problem_draft, edits_made, status, reviewer_id, review_notes, reviewed_at, created_at, updated_at
`

type UpdateProblemReviewStatusParams struct {
	ID          int64   `json:"id"`
	Status      string  `json:"status"`
	ReviewerID  *int64  `json:"reviewerId"`
	ReviewNotes *string `json:"reviewNotes"`
}

func (q *Queries) UpdateProblemReviewStatus(ctx context.Context, arg UpdateProblemReviewStatusParams) (ProblemReviewQueue, error) {
	row := q.db.QueryRow(ctx, updateProblemReviewStatus,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNotes,
	)
	var i ProblemReviewQueue
	err := row.Scan(
		&i.ID,
		&i.PdfUploadID,
		&i.ProblemNumber,
		&i.ProblemDraft,
		&i.EditsMade,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNotes,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTestCaseValidation = `-- name: UpdateTestCaseValidation :one
UPDATE test_case_templates
SET 
    is_validated = $2,
    validation_status = $3,
    validation_error = $4
WHERE id = $1
RETURNING id, problem_id, test_case_number, description, schema_sql, test_data_sql, expected_output, is_public, difficulty, is_validated, validation_status, validation_error, created_by, created_at
`

type UpdateTestCaseValidationParams struct {
	ID               int64   `json:"id"`
	IsValidated      *bool   `json:"isValidated"`
	ValidationStatus *string `json:"validationStatus"`
	ValidationError  *string `json:"validationError"`
}

func (q *Queries) UpdateTestCaseValidation(ctx context.Context, arg UpdateTestCaseValidationParams) (TestCaseTemplate, error) {
	row := q.db.QueryRow(ctx, updateTestCaseValidation,
		arg.ID,
		arg.IsValidated,
		arg.ValidationStatus,
		arg.ValidationError,
	)
	var i TestCaseTemplate
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.TestCaseNumber,
		&i.Description,
		&i.SchemaSql,
		&i.TestDataSql,
		&i.ExpectedOutput,
		&i.IsPublic,
		&i.Difficulty,
		&i.IsValidated,
		&i.ValidationStatus,
		&i.ValidationError,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
