// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPermissionGrant = `-- name: CheckPermissionGrant :one
SELECT EXISTS(
  SELECT 1 FROM permission_grants
  WHERE user_id = $1
    AND resource_type = $2
    AND resource_id = $3
    AND permission = $4
    AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
) AS has_grant
`

type CheckPermissionGrantParams struct {
	UserID       int64  `json:"userId"`
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	Permission   string `json:"permission"`
}

func (q *Queries) CheckPermissionGrant(ctx context.Context, arg CheckPermissionGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermissionGrant,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Permission,
	)
	var has_grant bool
	err := row.Scan(&has_grant)
	return has_grant, err
}

const cleanupExpiredPermissionGrants = `-- name: CleanupExpiredPermissionGrants :exec
DELETE FROM permission_grants
WHERE expires_at IS NOT NULL AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredPermissionGrants(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredPermissionGrants)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (user_id, action, resource_type, resource_id, old_value, new_value, reason, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, action, resource_type, resource_id, old_value, new_value, reason, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	UserID       *int64  `json:"userId"`
	Action       string  `json:"action"`
	ResourceType *string `json:"resourceType"`
	ResourceID   *int64  `json:"resourceId"`
	OldValue     []byte  `json:"oldValue"`
	NewValue     []byte  `json:"newValue"`
	Reason       *string `json:"reason"`
	IpAddress    *string `json:"ipAddress"`
	UserAgent    *string `json:"userAgent"`
}

// =============================================
// AUDIT LOG QUERIES
// =============================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (name, description, category)
VALUES ($1, $2, $3)
RETURNING id, name, description, category, created_at
`

type CreatePermissionParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Category    *string `json:"category"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Description, arg.Category)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createPermissionGrant = `-- name: CreatePermissionGrant :one
INSERT INTO permission_grants (user_id, resource_type, resource_id, permission, granted_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, resource_type, resource_id, permission) DO UPDATE
SET expires_at = EXCLUDED.expires_at, granted_by = EXCLUDED.granted_by
RETURNING id, user_id, resource_type, resource_id, permission, granted_at, granted_by, expires_at, created_at
`

type CreatePermissionGrantParams struct {
	UserID       int64              `json:"userId"`
	ResourceType string             `json:"resourceType"`
	ResourceID   int64              `json:"resourceId"`
	Permission   string             `json:"permission"`
	GrantedBy    int64              `json:"grantedBy"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreatePermissionGrant(ctx context.Context, arg CreatePermissionGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, createPermissionGrant,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Permission,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Permission,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_system)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at
`

type CreateRoleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsSystem    *bool   `json:"isSystem"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.IsSystem)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one

SELECT id, name, description, category, created_at FROM permissions WHERE id = $1
`

// =============================================
// PERMISSIONS QUERIES
// =============================================
func (q *Queries) GetPermissionByID(ctx context.Context, id int32) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, description, category, created_at FROM permissions WHERE name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionGrant = `-- name: GetPermissionGrant :one

SELECT id, user_id, resource_type, resource_id, permission, granted_at, granted_by, expires_at, created_at FROM permission_grants
WHERE user_id = $1 AND resource_type = $2 AND resource_id = $3 AND permission = $4
`

type GetPermissionGrantParams struct {
	UserID       int64  `json:"userId"`
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	Permission   string `json:"permission"`
}

// =============================================
// PERMISSION GRANTS QUERIES
// =============================================
func (q *Queries) GetPermissionGrant(ctx context.Context, arg GetPermissionGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getPermissionGrant,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Permission,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Permission,
		&i.GrantedAt,
		&i.GrantedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one

SELECT id, name, description, is_system, created_at FROM roles WHERE id = $1
`

// =============================================
// ROLES QUERIES
// =============================================
func (q *Queries) GetRoleByID(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many

SELECT p.id, p.name, p.description, p.category, p.created_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.category, p.name
`

// =============================================
// ROLE PERMISSIONS QUERIES
// =============================================
func (q *Queries) GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleIDs = `-- name: GetUserRoleIDs :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoleIDs(ctx context.Context, userID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var role_id int32
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT r.id, r.name, r.description, r.is_system, r.created_at FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

// =============================================
// USER ROLES QUERIES
// =============================================
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :one
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
RETURNING id, role_id, permission_id, created_at
`

type GrantPermissionToRoleParams struct {
	RoleID       int32 `json:"roleId"`
	PermissionID int32 `json:"permissionId"`
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, grantPermissionToRole, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}

const grantRoleToUser = `-- name: GrantRoleToUser :one
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
RETURNING id, user_id, role_id, assigned_at, assigned_by
`

type GrantRoleToUserParams struct {
	UserID     int64  `json:"userId"`
	RoleID     int32  `json:"roleId"`
	AssignedBy *int64 `json:"assignedBy"`
}

func (q *Queries) GrantRoleToUser(ctx context.Context, arg GrantRoleToUserParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, grantRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const isUserInRole = `-- name: IsUserInRole :one
SELECT EXISTS(
  SELECT 1 FROM user_roles
  WHERE user_id = $1 AND role_id = $2
) AS is_in_role
`

type IsUserInRoleParams struct {
	UserID int64 `json:"userId"`
	RoleID int32 `json:"roleId"`
}

func (q *Queries) IsUserInRole(ctx context.Context, arg IsUserInRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRole, arg.UserID, arg.RoleID)
	var is_in_role bool
	err := row.Scan(&is_in_role)
	return is_in_role, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, old_value, new_value, reason, ip_address, user_agent, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description, category, created_at FROM permissions ORDER BY category, name ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByCategory = `-- name: ListPermissionsByCategory :many
SELECT id, name, description, category, created_at FROM permissions WHERE category = $1 ORDER BY name ASC
`

func (q *Queries) ListPermissionsByCategory(ctx context.Context, category *string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceAuditLogs = `-- name: ListResourceAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, old_value, new_value, reason, ip_address, user_agent, created_at FROM audit_logs
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListResourceAuditLogsParams struct {
	ResourceType *string `json:"resourceType"`
	ResourceID   *int64  `json:"resourceId"`
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
}

func (q *Queries) ListResourceAuditLogs(ctx context.Context, arg ListResourceAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listResourceAuditLogs,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcePermissionGrants = `-- name: ListResourcePermissionGrants :many
SELECT id, user_id, resource_type, resource_id, permission, granted_at, granted_by, expires_at, created_at FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2
ORDER BY user_id, permission
`

type ListResourcePermissionGrantsParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
}

func (q *Queries) ListResourcePermissionGrants(ctx context.Context, arg ListResourcePermissionGrantsParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listResourcePermissionGrants, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Permission,
			&i.GrantedAt,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, created_at FROM roles ORDER BY name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAuditLogs = `-- name: ListUserAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, old_value, new_value, reason, ip_address, user_agent, created_at FROM audit_logs
WHERE user_id = $1 OR old_value->>'user_id' = $2::text OR new_value->>'user_id' = $2::text
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserAuditLogsParams struct {
	UserID  *int64 `json:"userId"`
	Column2 string `json:"column2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListUserAuditLogs(ctx context.Context, arg ListUserAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listUserAuditLogs,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionGrants = `-- name: ListUserPermissionGrants :many
SELECT id, user_id, resource_type, resource_id, permission, granted_at, granted_by, expires_at, created_at FROM permission_grants
WHERE user_id = $1
ORDER BY resource_type, resource_id, permission
`

func (q *Queries) ListUserPermissionGrants(ctx context.Context, userID int64) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listUserPermissionGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Permission,
			&i.GrantedAt,
			&i.GrantedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllResourcePermissionGrants = `-- name: RevokeAllResourcePermissionGrants :exec
DELETE FROM permission_grants
WHERE resource_type = $1 AND resource_id = $2
`

type RevokeAllResourcePermissionGrantsParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
}

func (q *Queries) RevokeAllResourcePermissionGrants(ctx context.Context, arg RevokeAllResourcePermissionGrantsParams) error {
	_, err := q.db.Exec(ctx, revokeAllResourcePermissionGrants, arg.ResourceType, arg.ResourceID)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       int32 `json:"roleId"`
	PermissionID int32 `json:"permissionId"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const revokePermissionGrant = `-- name: RevokePermissionGrant :exec
DELETE FROM permission_grants
WHERE user_id = $1 AND resource_type = $2 AND resource_id = $3 AND permission = $4
`

type RevokePermissionGrantParams struct {
	UserID       int64  `json:"userId"`
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	Permission   string `json:"permission"`
}

func (q *Queries) RevokePermissionGrant(ctx context.Context, arg RevokePermissionGrantParams) error {
	_, err := q.db.Exec(ctx, revokePermissionGrant,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Permission,
	)
	return err
}

const revokeRoleFromUser = `-- name: RevokeRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleFromUserParams struct {
	UserID int64 `json:"userId"`
	RoleID int32 `json:"roleId"`
}

func (q *Queries) RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, revokeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const roleHasPermission = `-- name: RoleHasPermission :one
SELECT EXISTS(
  SELECT 1 FROM role_permissions rp
  JOIN permissions p ON rp.permission_id = p.id
  WHERE rp.role_id = $1 AND p.name = $2
) AS has_permission
`

type RoleHasPermissionParams struct {
	RoleID int32  `json:"roleId"`
	Name   string `json:"name"`
}

func (q *Queries) RoleHasPermission(ctx context.Context, arg RoleHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, roleHasPermission, arg.RoleID, arg.Name)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET description = COALESCE($2, description)
WHERE id = $1
RETURNING id, name, description, is_system, created_at
`

type UpdateRoleParams struct {
	ID          int32   `json:"id"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS(
  SELECT 1 FROM user_roles ur
  JOIN role_permissions rp ON ur.role_id = rp.role_id
  JOIN permissions p ON rp.permission_id = p.id
  WHERE ur.user_id = $1 AND p.name = $2
) AS has_permission
`

type UserHasPermissionParams struct {
	UserID int64  `json:"userId"`
	Name   string `json:"name"`
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPermission, arg.UserID, arg.Name)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
