// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package models

import (
	"context"
)

const checkResourceAccess = `-- name: CheckResourceAccess :one
SELECT EXISTS(
  SELECT 1 FROM resource_access_control
  WHERE resource_type = $1
    AND resource_id = $2
    AND user_id = $3
    AND permission_type IN ('owner', 'editor', 'viewer')
) AS has_access
`

type CheckResourceAccessParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) CheckResourceAccess(ctx context.Context, arg CheckResourceAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkResourceAccess, arg.ResourceType, arg.ResourceID, arg.UserID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkResourceOwner = `-- name: CheckResourceOwner :one
SELECT EXISTS(
  SELECT 1 FROM resource_access_control
  WHERE resource_type = $1
    AND resource_id = $2
    AND user_id = $3
    AND permission_type = 'owner'
) AS is_owner
`

type CheckResourceOwnerParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) CheckResourceOwner(ctx context.Context, arg CheckResourceOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkResourceOwner, arg.ResourceType, arg.ResourceID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const checkUserHasPermission = `-- name: CheckUserHasPermission :one
SELECT EXISTS(
  SELECT 1 FROM user_roles ur
  JOIN role_permissions rp ON ur.role_id = rp.role_id
  JOIN permissions p ON rp.permission_id = p.id
  WHERE ur.user_id = $1
    AND p.resource_type = $2
    AND p.action = $3
) AS has_permission
`

type CheckUserHasPermissionParams struct {
	UserID       int32  `json:"userId"`
	ResourceType string `json:"resourceType"`
	Action       string `json:"action"`
}

func (q *Queries) CheckUserHasPermission(ctx context.Context, arg CheckUserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasPermission, arg.UserID, arg.ResourceType, arg.Action)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO permission_audit_log (action, target_user_id, target_role_id, target_resource_type, target_resource_id, performed_by, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, action, target_user_id, target_role_id, target_resource_type, target_resource_id, performed_by, details, created_at
`

type CreateAuditLogParams struct {
	Action             string  `json:"action"`
	TargetUserID       *int32  `json:"targetUserId"`
	TargetRoleID       *int32  `json:"targetRoleId"`
	TargetResourceType *string `json:"targetResourceType"`
	TargetResourceID   *int64  `json:"targetResourceId"`
	PerformedBy        int32   `json:"performedBy"`
	Details            []byte  `json:"details"`
}

// =============================================
// AUDIT LOG QUERIES
// =============================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (PermissionAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.Action,
		arg.TargetUserID,
		arg.TargetRoleID,
		arg.TargetResourceType,
		arg.TargetResourceID,
		arg.PerformedBy,
		arg.Details,
	)
	var i PermissionAuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetUserID,
		&i.TargetRoleID,
		&i.TargetResourceType,
		&i.TargetResourceID,
		&i.PerformedBy,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (resource_type, action, description)
VALUES ($1, $2, $3)
RETURNING id, resource_type, action, description, created_at
`

type CreatePermissionParams struct {
	ResourceType string  `json:"resourceType"`
	Action       string  `json:"action"`
	Description  *string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.ResourceType, arg.Action, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createResourceAccess = `-- name: CreateResourceAccess :one

INSERT INTO resource_access_control (resource_type, resource_id, user_id, permission_type, granted_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (resource_type, resource_id, user_id, permission_type) DO NOTHING
RETURNING id, resource_type, resource_id, user_id, permission_type, granted_at, granted_by
`

type CreateResourceAccessParams struct {
	ResourceType   string `json:"resourceType"`
	ResourceID     int64  `json:"resourceId"`
	UserID         int32  `json:"userId"`
	PermissionType string `json:"permissionType"`
	GrantedBy      *int32 `json:"grantedBy"`
}

// =============================================
// RESOURCE ACCESS CONTROL QUERIES
// =============================================
func (q *Queries) CreateResourceAccess(ctx context.Context, arg CreateResourceAccessParams) (ResourceAccessControl, error) {
	row := q.db.QueryRow(ctx, createResourceAccess,
		arg.ResourceType,
		arg.ResourceID,
		arg.UserID,
		arg.PermissionType,
		arg.GrantedBy,
	)
	var i ResourceAccessControl
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.UserID,
		&i.PermissionType,
		&i.GrantedAt,
		&i.GrantedBy,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_extensible)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_extensible, created_at, updated_at
`

type CreateRoleParams struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	IsExtensible *bool   `json:"isExtensible"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.IsExtensible)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsExtensible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getAuditLog = `-- name: GetAuditLog :many
SELECT id, action, target_user_id, target_role_id, target_resource_type, target_resource_id, performed_by, details, created_at FROM permission_audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAuditLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAuditLog(ctx context.Context, arg GetAuditLogParams) ([]PermissionAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionAuditLog{}
	for rows.Next() {
		var i PermissionAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetUserID,
			&i.TargetRoleID,
			&i.TargetResourceType,
			&i.TargetResourceID,
			&i.PerformedBy,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one

SELECT id, resource_type, action, description, created_at FROM permissions WHERE id = $1
`

// =============================================
// PERMISSIONS QUERIES
// =============================================
func (q *Queries) GetPermissionByID(ctx context.Context, id int32) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.Action,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getResourceAccess = `-- name: GetResourceAccess :many
SELECT id, resource_type, resource_id, user_id, permission_type, granted_at, granted_by FROM resource_access_control
WHERE resource_type = $1 AND resource_id = $2
ORDER BY permission_type, user_id
`

type GetResourceAccessParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
}

func (q *Queries) GetResourceAccess(ctx context.Context, arg GetResourceAccessParams) ([]ResourceAccessControl, error) {
	rows, err := q.db.Query(ctx, getResourceAccess, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceAccessControl{}
	for rows.Next() {
		var i ResourceAccessControl
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.UserID,
			&i.PermissionType,
			&i.GrantedAt,
			&i.GrantedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one

SELECT id, name, description, is_extensible, created_at, updated_at FROM roles WHERE id = $1
`

// =============================================
// ROLES QUERIES
// =============================================
func (q *Queries) GetRoleByID(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsExtensible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_extensible, created_at, updated_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsExtensible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many

SELECT p.id, p.resource_type, p.action, p.description, p.created_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.resource_type, p.action
`

// =============================================
// ROLE PERMISSIONS QUERIES
// =============================================
func (q *Queries) GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuditLog = `-- name: GetUserAuditLog :many
SELECT id, action, target_user_id, target_role_id, target_resource_type, target_resource_id, performed_by, details, created_at FROM permission_audit_log
WHERE target_user_id = $1 OR performed_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserAuditLogParams struct {
	TargetUserID *int32 `json:"targetUserId"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) GetUserAuditLog(ctx context.Context, arg GetUserAuditLogParams) ([]PermissionAuditLog, error) {
	rows, err := q.db.Query(ctx, getUserAuditLog, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionAuditLog{}
	for rows.Next() {
		var i PermissionAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetUserID,
			&i.TargetRoleID,
			&i.TargetResourceType,
			&i.TargetResourceID,
			&i.PerformedBy,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserResourceAccess = `-- name: GetUserResourceAccess :many
SELECT id, resource_type, resource_id, user_id, permission_type, granted_at, granted_by FROM resource_access_control
WHERE user_id = $1 AND resource_type = $2
ORDER BY permission_type
`

type GetUserResourceAccessParams struct {
	UserID       int32  `json:"userId"`
	ResourceType string `json:"resourceType"`
}

func (q *Queries) GetUserResourceAccess(ctx context.Context, arg GetUserResourceAccessParams) ([]ResourceAccessControl, error) {
	rows, err := q.db.Query(ctx, getUserResourceAccess, arg.UserID, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceAccessControl{}
	for rows.Next() {
		var i ResourceAccessControl
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.UserID,
			&i.PermissionType,
			&i.GrantedAt,
			&i.GrantedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleIDs = `-- name: GetUserRoleIDs :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoleIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var role_id int32
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT r.id, r.name, r.description, r.is_extensible, r.created_at, r.updated_at FROM roles r
JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

// =============================================
// USER ROLES QUERIES
// =============================================
func (q *Queries) GetUserRoles(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsExtensible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :one
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
RETURNING id, role_id, permission_id, created_at
`

type GrantPermissionToRoleParams struct {
	RoleID       int32 `json:"roleId"`
	PermissionID int32 `json:"permissionId"`
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, grantPermissionToRole, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
	)
	return i, err
}

const grantRoleToUser = `-- name: GrantRoleToUser :one
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
RETURNING id, user_id, role_id, assigned_at, assigned_by
`

type GrantRoleToUserParams struct {
	UserID     int32  `json:"userId"`
	RoleID     int32  `json:"roleId"`
	AssignedBy *int32 `json:"assignedBy"`
}

func (q *Queries) GrantRoleToUser(ctx context.Context, arg GrantRoleToUserParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, grantRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS(
  SELECT 1 FROM role_permissions rp
  JOIN permissions p ON rp.permission_id = p.id
  WHERE rp.role_id = $1
    AND p.resource_type = $2
    AND p.action = $3
) AS has_permission
`

type HasPermissionParams struct {
	RoleID       int32  `json:"roleId"`
	ResourceType string `json:"resourceType"`
	Action       string `json:"action"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.RoleID, arg.ResourceType, arg.Action)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const isUserInRole = `-- name: IsUserInRole :one
SELECT EXISTS(
  SELECT 1 FROM user_roles
  WHERE user_id = $1 AND role_id = $2
) AS is_in_role
`

type IsUserInRoleParams struct {
	UserID int32 `json:"userId"`
	RoleID int32 `json:"roleId"`
}

func (q *Queries) IsUserInRole(ctx context.Context, arg IsUserInRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRole, arg.UserID, arg.RoleID)
	var is_in_role bool
	err := row.Scan(&is_in_role)
	return is_in_role, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, resource_type, action, description, created_at FROM permissions ORDER BY resource_type, action ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByResourceType = `-- name: ListPermissionsByResourceType :many
SELECT id, resource_type, action, description, created_at FROM permissions WHERE resource_type = $1 ORDER BY action ASC
`

func (q *Queries) ListPermissionsByResourceType(ctx context.Context, resourceType string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByResourceType, resourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.Action,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_extensible, created_at, updated_at FROM roles ORDER BY id ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsExtensible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllResourceAccess = `-- name: RevokeAllResourceAccess :exec
DELETE FROM resource_access_control
WHERE resource_type = $1 AND resource_id = $2
`

type RevokeAllResourceAccessParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
}

func (q *Queries) RevokeAllResourceAccess(ctx context.Context, arg RevokeAllResourceAccessParams) error {
	_, err := q.db.Exec(ctx, revokeAllResourceAccess, arg.ResourceType, arg.ResourceID)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       int32 `json:"roleId"`
	PermissionID int32 `json:"permissionId"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const revokeResourceAccess = `-- name: RevokeResourceAccess :exec
DELETE FROM resource_access_control
WHERE resource_type = $1 AND resource_id = $2 AND user_id = $3
`

type RevokeResourceAccessParams struct {
	ResourceType string `json:"resourceType"`
	ResourceID   int64  `json:"resourceId"`
	UserID       int32  `json:"userId"`
}

func (q *Queries) RevokeResourceAccess(ctx context.Context, arg RevokeResourceAccessParams) error {
	_, err := q.db.Exec(ctx, revokeResourceAccess, arg.ResourceType, arg.ResourceID, arg.UserID)
	return err
}

const revokeRoleFromUser = `-- name: RevokeRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleFromUserParams struct {
	UserID int32 `json:"userId"`
	RoleID int32 `json:"roleId"`
}

func (q *Queries) RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, revokeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = COALESCE($2, name),
                 description = COALESCE($3, description),
                 is_extensible = COALESCE($4, is_extensible),
                 updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, is_extensible, created_at, updated_at
`

type UpdateRoleParams struct {
	ID           int32   `json:"id"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
	IsExtensible *bool   `json:"isExtensible"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsExtensible,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsExtensible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
