// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_case.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProblemTestCase = `-- name: CreateProblemTestCase :one
INSERT INTO problem_test_cases (
    problem_id, name, description, init_script, solution_query, weight, is_hidden
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, problem_id, name, description, init_script, solution_query, weight, is_hidden, created_at, updated_at
`

type CreateProblemTestCaseParams struct {
	ProblemID     int64   `json:"problemId"`
	Name          *string `json:"name"`
	Description   *string `json:"description"`
	InitScript    string  `json:"initScript"`
	SolutionQuery string  `json:"solutionQuery"`
	Weight        *int32  `json:"weight"`
	IsHidden      *bool   `json:"isHidden"`
}

func (q *Queries) CreateProblemTestCase(ctx context.Context, arg CreateProblemTestCaseParams) (ProblemTestCase, error) {
	row := q.db.QueryRow(ctx, createProblemTestCase,
		arg.ProblemID,
		arg.Name,
		arg.Description,
		arg.InitScript,
		arg.SolutionQuery,
		arg.Weight,
		arg.IsHidden,
	)
	var i ProblemTestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Name,
		&i.Description,
		&i.InitScript,
		&i.SolutionQuery,
		&i.Weight,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmissionTestResult = `-- name: CreateSubmissionTestResult :one
INSERT INTO submission_test_results (
    submission_id, test_case_id, status, execution_time_ms, actual_output, error_message, is_correct
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, submission_id, test_case_id, status, execution_time_ms, actual_output, error_message, is_correct, created_at
`

type CreateSubmissionTestResultParams struct {
	SubmissionID    int64   `json:"submissionId"`
	TestCaseID      int64   `json:"testCaseId"`
	Status          string  `json:"status"`
	ExecutionTimeMs *int32  `json:"executionTimeMs"`
	ActualOutput    []byte  `json:"actualOutput"`
	ErrorMessage    *string `json:"errorMessage"`
	IsCorrect       *bool   `json:"isCorrect"`
}

func (q *Queries) CreateSubmissionTestResult(ctx context.Context, arg CreateSubmissionTestResultParams) (SubmissionTestResult, error) {
	row := q.db.QueryRow(ctx, createSubmissionTestResult,
		arg.SubmissionID,
		arg.TestCaseID,
		arg.Status,
		arg.ExecutionTimeMs,
		arg.ActualOutput,
		arg.ErrorMessage,
		arg.IsCorrect,
	)
	var i SubmissionTestResult
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.TestCaseID,
		&i.Status,
		&i.ExecutionTimeMs,
		&i.ActualOutput,
		&i.ErrorMessage,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllProblemTestCases = `-- name: DeleteAllProblemTestCases :exec
DELETE FROM problem_test_cases WHERE problem_id = $1
`

func (q *Queries) DeleteAllProblemTestCases(ctx context.Context, problemID int64) error {
	_, err := q.db.Exec(ctx, deleteAllProblemTestCases, problemID)
	return err
}

const deleteProblemTestCase = `-- name: DeleteProblemTestCase :exec
DELETE FROM problem_test_cases WHERE id = $1
`

func (q *Queries) DeleteProblemTestCase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProblemTestCase, id)
	return err
}

const getProblemTestCaseByID = `-- name: GetProblemTestCaseByID :one
SELECT id, problem_id, name, description, init_script, solution_query, weight, is_hidden, created_at, updated_at FROM problem_test_cases WHERE id = $1
`

func (q *Queries) GetProblemTestCaseByID(ctx context.Context, id int64) (ProblemTestCase, error) {
	row := q.db.QueryRow(ctx, getProblemTestCaseByID, id)
	var i ProblemTestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Name,
		&i.Description,
		&i.InitScript,
		&i.SolutionQuery,
		&i.Weight,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProblemTestCases = `-- name: ListProblemTestCases :many
SELECT id, problem_id, name, description, init_script, solution_query, weight, is_hidden, created_at, updated_at FROM problem_test_cases
WHERE problem_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProblemTestCases(ctx context.Context, problemID int64) ([]ProblemTestCase, error) {
	rows, err := q.db.Query(ctx, listProblemTestCases, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemTestCase{}
	for rows.Next() {
		var i ProblemTestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.Name,
			&i.Description,
			&i.InitScript,
			&i.SolutionQuery,
			&i.Weight,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionTestResults = `-- name: ListSubmissionTestResults :many
SELECT tr.id, tr.submission_id, tr.test_case_id, tr.status, tr.execution_time_ms, tr.actual_output, tr.error_message, tr.is_correct, tr.created_at, tc.name as test_case_name, tc.is_hidden
FROM submission_test_results tr
JOIN problem_test_cases tc ON tc.id = tr.test_case_id
WHERE tr.submission_id = $1
ORDER BY tc.created_at ASC
`

type ListSubmissionTestResultsRow struct {
	ID              int64              `json:"id"`
	SubmissionID    int64              `json:"submissionId"`
	TestCaseID      int64              `json:"testCaseId"`
	Status          string             `json:"status"`
	ExecutionTimeMs *int32             `json:"executionTimeMs"`
	ActualOutput    []byte             `json:"actualOutput"`
	ErrorMessage    *string            `json:"errorMessage"`
	IsCorrect       *bool              `json:"isCorrect"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	TestCaseName    *string            `json:"testCaseName"`
	IsHidden        *bool              `json:"isHidden"`
}

func (q *Queries) ListSubmissionTestResults(ctx context.Context, submissionID int64) ([]ListSubmissionTestResultsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionTestResults, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionTestResultsRow{}
	for rows.Next() {
		var i ListSubmissionTestResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.TestCaseID,
			&i.Status,
			&i.ExecutionTimeMs,
			&i.ActualOutput,
			&i.ErrorMessage,
			&i.IsCorrect,
			&i.CreatedAt,
			&i.TestCaseName,
			&i.IsHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblemTestCase = `-- name: UpdateProblemTestCase :one
UPDATE problem_test_cases SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    init_script = COALESCE($4, init_script),
    solution_query = COALESCE($5, solution_query),
    weight = COALESCE($6, weight),
    is_hidden = COALESCE($7, is_hidden),
    updated_at = NOW()
WHERE id = $1
RETURNING id, problem_id, name, description, init_script, solution_query, weight, is_hidden, created_at, updated_at
`

type UpdateProblemTestCaseParams struct {
	ID            int64   `json:"id"`
	Name          *string `json:"name"`
	Description   *string `json:"description"`
	InitScript    *string `json:"initScript"`
	SolutionQuery *string `json:"solutionQuery"`
	Weight        *int32  `json:"weight"`
	IsHidden      *bool   `json:"isHidden"`
}

func (q *Queries) UpdateProblemTestCase(ctx context.Context, arg UpdateProblemTestCaseParams) (ProblemTestCase, error) {
	row := q.db.QueryRow(ctx, updateProblemTestCase,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.InitScript,
		arg.SolutionQuery,
		arg.Weight,
		arg.IsHidden,
	)
	var i ProblemTestCase
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Name,
		&i.Description,
		&i.InitScript,
		&i.SolutionQuery,
		&i.Weight,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionScore = `-- name: UpdateSubmissionScore :exec
UPDATE submissions SET
    score = $2,
    total_test_cases = $3,
    passed_test_cases = $4
WHERE id = $1
`

type UpdateSubmissionScoreParams struct {
	ID              int64          `json:"id"`
	Score           pgtype.Numeric `json:"score"`
	TotalTestCases  *int32         `json:"totalTestCases"`
	PassedTestCases *int32         `json:"passedTestCases"`
}

func (q *Queries) UpdateSubmissionScore(ctx context.Context, arg UpdateSubmissionScoreParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionScore,
		arg.ID,
		arg.Score,
		arg.TotalTestCases,
		arg.PassedTestCases,
	)
	return err
}
