// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topic.sql

package models

import (
	"context"
)

const countProblemsPerTopic = `-- name: CountProblemsPerTopic :many
SELECT t.id, t.name, t.slug, COUNT(p.id) as problem_count
FROM topics t
LEFT JOIN problems p ON p.topic_id = t.id AND p.is_active = TRUE
WHERE t.is_active = TRUE
GROUP BY t.id
ORDER BY t.sort_order ASC
`

type CountProblemsPerTopicRow struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	ProblemCount int64  `json:"problemCount"`
}

func (q *Queries) CountProblemsPerTopic(ctx context.Context) ([]CountProblemsPerTopicRow, error) {
	rows, err := q.db.Query(ctx, countProblemsPerTopic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProblemsPerTopicRow{}
	for rows.Next() {
		var i CountProblemsPerTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ProblemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (name, slug, description, icon, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, icon, sort_order, is_active, created_at
`

type CreateTopicParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
	SortOrder   *int32  `json:"sortOrder"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.SortOrder,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
UPDATE topics SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, name, slug, description, icon, sort_order, is_active, created_at FROM topics WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id int32) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicBySlug = `-- name: GetTopicBySlug :one
SELECT id, name, slug, description, icon, sort_order, is_active, created_at FROM topics WHERE slug = $1
`

func (q *Queries) GetTopicBySlug(ctx context.Context, slug string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicBySlug, slug)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, slug, description, icon, sort_order, is_active, created_at FROM topics 
WHERE is_active = TRUE
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    icon = COALESCE($4, icon),
    sort_order = COALESCE($5, sort_order)
WHERE id = $1
RETURNING id, name, slug, description, icon, sort_order, is_active, created_at
`

type UpdateTopicParams struct {
	ID          int32   `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Icon        *string `json:"icon"`
	SortOrder   *int32  `json:"sortOrder"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.SortOrder,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
