services:
  sqlexam.postgres:
    image: postgres:16-alpine
    container_name: sqlexam.postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-123456}
      POSTGRES_DB: ${DATABASE_NAME:-sql_exam_db}
    ports:
      - "5432:5432"
    volumes:
      - sqlexam_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sql_exam_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sqlexam_postgres_data:
    name: sqlexam_postgres_data
