export const API_ENDPOINTS = {
    auth: {
        login: '/auth/login',
        register: '/auth/register',
        logout: '/auth/logout',
    },
    topics: {
        list: '/topics',
        bySlug: (slug: string) => `/topics/${slug}`,
        create: '/topics',
    },
    problems: {
        list: '/problems',
        bySlug: (slug: string) => `/problems/${slug}`,
        create: '/problems',
        update: (id: number) => `/problems/${id}`,
        delete: (id: number) => `/problems/${id}`,
        run: (id: number) => `/problems/${id}/run`,
        submit: (id: number) => `/problems/${id}/submit`,
    },
    submissions: {
        list: '/submissions',
    },
    exams: {
        list: '/exams',
        create: '/exams',
        byId: (id: number) => `/exams/${id}`,
        addProblem: (id: number) => `/exams/${id}/problems`,
        addParticipants: (id: number) => `/exams/${id}/participants`,
        listParticipants: (id: number) => `/exams/${id}/participants`,
        myExams: '/my-exams',
    },
    admin: {
        stats: '/admin/stats',
        users: '/admin/users',
        importUsers: '/admin/users/import',
        updateRole: (id: number) => `/admin/users/${id}/role`,
        toggleActive: (id: number) => `/admin/users/${id}/active`,
        sandboxStatus: '/admin/sandbox/status',
        sandboxTest: '/admin/sandbox/test',
    },
    pdf: {
        upload: '/lecturer/pdf/upload',
        status: (id: number) => `/lecturer/pdf/${id}/status`,
        problems: (id: number) => `/lecturer/pdf/${id}/problems`,
        updateSolution: (id: number) => `/lecturer/pdf/problems/${id}/solution`,
        confirmProblem: (id: number) => `/lecturer/pdf/problems/${id}/confirm`,
    },
    lecturer: {
        ungradedSubmissions: (examId: number) => `/lecturer/exams/${examId}/ungraded`,
        gradingStats: (examId: number) => `/lecturer/exams/${examId}/grading-stats`,
        viewSubmission: (submissionId: number) => `/lecturer/submissions/${submissionId}`,
        gradeSubmission: (submissionId: number) => `/lecturer/submissions/${submissionId}/grade`,
        bulkGrade: '/lecturer/submissions/bulk-grade',
    },
    student: {
        results: '/student/results',
    },
    health: '/health',
} as const
